### PR TITLE
Prevent duplicated addresses in avm import key

### LINKED ISSUE #243: `avm.importKey` create duplicates
**Describe the bug**
If you perform multiple time the same call to the AVM `importKey`, the address linked to the private key is added each time to the list of address owned by the user.

image

**To Reproduce**
Perform multiple times the call to `avm.importKey` wit the same `privateKey` .

**Expected behavior**
Imho it should be the same behaviour as for `platform.importKey` , which does not create duplicates as per my tests 

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

### PR DESCRIPTION
**Pull request by aaronbuchwald**
Fixes #243

### CODE REVIEW

File: vms/avm/service.go [hunk 1]
```diff
@@ -665,14 +665,26 @@ func (service *Service) ImportKey(r *http.Request, args *ImportKeyArgs, reply *I
...
 
-	if err := user.SetAddresses(db, addresses); err != nil {
-		return fmt.Errorf("problem saving addresses: %w", err)
+		if err := user.SetAddresses(db, addresses); err != nil {
+			return fmt.Errorf("problem saving addresses: %w", err)
+		}
 	}
 
-	reply.Address = service.vm.Format(sk.PublicKey().Address().Bytes())
+	reply.Address = service.vm.Format(newAddress.Bytes())
```
Comment (StephenButtolph) [inline vms/avm/service.go:687]: If we move
```
reply.Address = service.vm.Format(newAddress.Bytes())
```
 up to where we define `newAddress`, then we could just `return nil` inside the duplication check, and then we'll have removed the need for the `exists` variable.

Comment (aaronbuchwald) [reply vms/avm/service.go]: Fixed

File: vms/avm/service.go [hunk 2]
```diff
@@ -666,13 +666,21 @@ func (service *Service) ImportKey(r *http.Request, args *ImportKeyArgs, reply *I
...
+	}
+
+	addresses = append(addresses, newAddress)
 	if err := user.SetAddresses(db, addresses); err != nil {
 		return fmt.Errorf("problem saving addresses: %w", err)
 	}
 
-	reply.Address = service.vm.Format(sk.PublicKey().Address().Bytes())
+	reply.Address = service.vm.Format(newAddress.Bytes())
 	return nil
```
Comment (StephenButtolph) [inline vms/avm/service.go:684]: Super minor nit, but this can just be:
```
newAddress := sk.PublicKey().Address()
reply.Address = service.vm.Format(newAddress.Bytes())
for _, address := range addresses {
	if newAddress.Equals(address) {
		return nil
	}
}

addresses = append(addresses, newAddress)
if err := user.SetAddresses(db, addresses); err != nil {
	return fmt.Errorf("problem saving addresses: %w", err)
}
return nil
```

Comment (aaronbuchwald) [reply vms/avm/service.go]: Updated
