### PR TITLE
Go signals

### LINKED ISSUE #8: Crash on Exit
**Describe the bug**
Sometimes when gecko is exited, the node will crash due to an "unexpected return pc" I believe this is a bug with how we are using defer statements along with our use of cgo.

**To Reproduce**
Start a node and then Ctrl + C it after some time. Repeat until the node crashes.

**Expected behavior**
Ctrl + C should always gracefully exit.

**Screenshots**
Here is an example stacktrace.

```
unexpected fault address 0xbfe1062ad1
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0xbfe1062ad1 pc=0x495fe5]

goroutine 167 [running]:
runtime.throw(0x11aa99d, 0x5)
        /home/stephen/.gvm/gos/go1.13/src/runtime/panic.go:774 +0x72 fp=0xc0004f5700 sp=0xc0004f56d0 pc=0x465142
runtime.sigpanic()
        /home/stephen/.gvm/gos/go1.13/src/runtime/signal_unix.go:401 +0x3de fp=0xc0004f5730 sp=0xc0004f5700 pc=0x47a95e
runtime.memmove(0xc0004f5780, 0xc0004f57b8, 0xffffffffe0b6d399)
        /home/stephen/.gvm/gos/go1.13/src/runtime/memmove_amd64.s:390 +0x485 fp=0xc0004f5738 sp=0xc0004f5730 pc=0x495fe5
runtime.deferreturn(0xc0004f5788)
        /home/stephen/.gvm/gos/go1.13/src/runtime/panic.go:525 +0xf7 fp=0xc0004f5780 sp=0xc0004f5738 pc=0x4647a7
runtime: unexpected return pc for github.com/ava-labs/gecko/utils/logging.(*Log).RecoverAndPanic called from 0x7fbde186fc65
stack: frame={sp:0xc0004f5780, fp:0xc0004f57d0} stack=[0xc0004f5000,0xc0004f5800)
000000c0004f5680:  000000c0004f56d0  00000000004664d8 <runtime.printstring+120>
000000c0004f5690:  0000000000465317 <runtime.fatalthrow+87>  000000c0004f56a0
000000c0004f56a0:  0000000000491530 <runtime.fatalthrow.func1+0>  000000c0000a0c00
000000c0004f56b0:  0000000000465142 <runtime.throw+114>  000000c0004f56d0
000000c0004f56c0:  000000c0004f56f0  0000000000465142 <runtime.throw+114>
000000c0004f56d0:  000000c0004f56d8  00000000004914b0 <runtime.throw.func1+0>
000000c0004f56e0:  00000000011aa99d  0000000000000005
000000c0004f56f0:  000000c0004f5720  000000000047a95e <runtime.sigpanic+990>
000000c0004f5700:  00000000011aa99d  0000000000000005
000000c0004f5710:  000000c0002982e8  000000bfe1062ad1
000000c0004f5720:  000000c0004f5770  0000000000495fe5 <runtime.memmove+1157>
000000c0004f5730:  00000000004647a7 <runtime.deferreturn+247>  000000c0004f5780
000000c0004f5740:  000000c0004f57b8  ffffffffe0b6d399
000000c0004f5750:  000000c0000a0c00  000000c0004f5770
000000c0004f5760:  000000c0004f5788  000000c000298240
000000c0004f5770:  000000c0004f57c0  0000000000800f8d <github.com/ava-labs/gecko/utils/logging.(*Log).RecoverAndPanic+93>
000000c0004f5780: <000000c0004f5788  00007fbde0b6d399
000000c0004f5790:  000000c0004f5780  00007fbde0b6d2cc
000000c0004f57a0:  00007fbde1a81b60  0000000000000001
000000c0004f57b0:  000000c0004f57d7  00007fbde1c836a0
000000c0004f57c0:  000000c0004f57f0 !00007fbde186fc65
000000c0004f57d0: >2a00000002a41c90  2f3ad2ca4a668400
000000c0004f57e0:  0000000002a41d70  00007fbde18700ed
000000c0004f57f0:  0000000002a41c90  0000000000000002
github.com/ava-labs/gecko/utils/logging.(*Log).RecoverAndPanic(0x2a00000002a41c90, 0x2f3ad2ca4a668400)
        /home/stephen/go/src/github.com/ava-labs/gecko/utils/logging/log.go:254 +0x5d fp=0xc0004f57d0 sp=0xc0004f5780 pc=0x800f8d
created by github.com/ava-labs/gecko/utils/logging.New
        /home/stephen/go/src/github.com/ava-labs/gecko/utils/logging/log.go:42 +0x14e

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc000032500)
        /home/stephen/.gvm/gos/go1.13/src/runtime/sema.go:56 +0x42
sync.(*WaitGroup).Wait(0xc0000324f8)
        /home/stephen/.gvm/gos/go1.13/src/sync/waitgroup.go:130 +0x64
github.com/ava-labs/gecko/utils/logging.(*Log).Stop(0xc000032480)
        /home/stephen/go/src/github.com/ava-labs/gecko/utils/logging/log.go:119 +0x85
github.com/ava-labs/gecko/utils/logging.(*factory).Close(0xc00022f490)
        /home/stephen/go/src/github.com/ava-labs/gecko/utils/logging/factory.go:71 +0x63
main.main()
        /home/stephen/go/src/github.com/ava-labs/gecko/main/main.go:102 +0xa08

goroutine 8 [chan receive, 33 minutes]:
github.com/ava-labs/go-ethereum/core.(*txSenderCacher).cache(0xc000195510)
        /home/stephen/go/src/github.com/ava-labs/go-ethereum/core/tx_cacher.go:63 +0x97
created by github.com/ava-labs/go-ethereum/core.newTxSenderCacher
        /home/stephen/go/src/github.com/ava-labs/go-ethereum/core/tx_cacher.go:55 +0x9f

goroutine 9 [chan receive, 33 minutes]:
github.com/ava-labs/go-ethereum/core.(*txSenderCacher).cache(0xc000195510)
        /home/stephen/go/src/github.com/ava-labs/go-ethereum/core/tx_cacher.go:63 +0x97
created by github.com/ava-labs/go-ethereum/core.newTxSenderCacher
        /home/stephen/go/src/github.com/ava-labs/go-ethereum/core/tx_cacher.go:55 +0x9f

goroutine 10 [chan receive, 33 minutes]:
github.com/ava-labs/go-ethereum/core.(*txSenderCacher).cache(0xc000195510)
        /home/stephen/go/src/github.com/ava-labs/go-ethereum/core/tx_cacher.go:63 +0x97
created by github.com/ava-labs/go-ethereum/core.newTxSenderCacher
        /home/stephen/go/src/github.com/ava-labs/go-ethereum/core/tx_cacher.go:55 +0x9f

goroutine 11 [chan receive, 33 minutes]:
github.com/ava-labs/go-ethereum/core.(*txSenderCacher).cache(0xc000195510)
        /home/stephen/go/src/github.com/ava-labs/go-ethereum/core/tx_cacher.go:63 +0x97
created by github.com/ava-labs/go-ethereum/core.newTxSenderCacher
        /home/stephen/go/src/github.com/ava-labs/go-ethereum/core/tx_cacher.go:55 +0x9f

goroutine 12 [chan receive, 33 minutes]:
github.com/ava-labs/go-ethereum/core.(*txSenderCacher).cache(0xc000195510)
        /home/stephen/go/src/github.com/ava-labs/go-ethereum/core/tx_cacher.go:63 +0x97
created by github.com/ava-labs/go-ethereum/core.newTxSenderCacher
        /home/stephen/go/src/github.com/ava-labs/go-ethereum/core/tx_cacher.go:55 +0x9f

goroutine 13 [chan receive, 33 minutes]:
github.com/ava-labs/go-ethereum/core.(*txSenderCacher).cache(0xc000195510)
        /home/stephen/go/src/github.com/ava-labs/go-ethereum/core/tx_cacher.go:63 +0x97
created by github.com/ava-labs/go-ethereum/core.newTxSenderCacher
        /home/stephen/go/src/github.com/ava-labs/go-ethereum/core/tx_cacher.go:55 +0x9f

goroutine 14 [chan receive, 33 minutes]:
github.com/ava-labs/go-ethereum/core.(*txSenderCacher).cache(0xc000195510)
        /home/stephen/go/src/github.com/ava-labs/go-ethereum/core/tx_cacher.go:63 +0x97
created by github.com/ava-labs/go-ethereum/core.newTxSenderCacher
        /home/stephen/go/src/github.com/ava-labs/go-ethereum/core/tx_cacher.go:55 +0x9f

goroutine 15 [chan receive, 33 minutes]:
github.com/ava-labs/go-ethereum/core.(*txSenderCacher).cache(0xc000195510)
        /home/stephen/go/src/github.com/ava-labs/go-ethereum/core/tx_cacher.go:63 +0x97
created by github.com/ava-labs/go-ethereum/core.newTxSenderCacher
        /home/stephen/go/src/github.com/ava-labs/go-ethereum/core/tx_cacher.go:55 +0x9f

goroutine 16 [chan receive, 33 minutes]:
github.com/ava-labs/coreth/core.(*txSenderCacher).cache(0xc000195770)
        /home/stephen/go/src/github.com/ava-labs/coreth/core/tx_cacher.go:63 +0x97
created by github.com/ava-labs/coreth/core.newTxSenderCacher
        /home/stephen/go/src/github.com/ava-labs/coreth/core/tx_cacher.go:55 +0x9f

goroutine 34 [chan receive, 33 minutes]:
github.com/ava-labs/coreth/core.(*txSenderCacher).cache(0xc000195770)
        /home/stephen/go/src/github.com/ava-labs/coreth/core/tx_cacher.go:63 +0x97
created by github.com/ava-labs/coreth/core.newTxSenderCacher
        /home/stephen/go/src/github.com/ava-labs/coreth/core/tx_cacher.go:55 +0x9f

goroutine 35 [chan receive, 33 minutes]:
github.com/ava-labs/coreth/core.(*txSenderCacher).cache(0xc000195770)
        /home/stephen/go/src/github.com/ava-labs/coreth/core/tx_cacher.go:63 +0x97
created by github.com/ava-labs/coreth/core.newTxSenderCacher
        /home/stephen/go/src/github.com/ava-labs/coreth/core/tx_cacher.go:55 +0x9f

goroutine 36 [chan receive, 33 minutes]:
github.com/ava-labs/coreth/core.(*txSenderCacher).cache(0xc000195770)
        /home/stephen/go/src/github.com/ava-labs/coreth/core/tx_cacher.go:63 +0x97
created by github.com/ava-labs/coreth/core.newTxSenderCacher
        /home/stephen/go/src/github.com/ava-labs/coreth/core/tx_cacher.go:55 +0x9f

goroutine 37 [chan receive, 33 minutes]:
github.com/ava-labs/coreth/core.(*txSenderCacher).cache(0xc000195770)
        /home/stephen/go/src/github.com/ava-labs/coreth/core/tx_cacher.go:63 +0x97
created by github.com/ava-labs/coreth/core.newTxSenderCacher
        /home/stephen/go/src/github.com/ava-labs/coreth/core/tx_cacher.go:55 +0x9f

goroutine 38 [chan receive, 33 minutes]:
github.com/ava-labs/coreth/core.(*txSenderCacher).cache(0xc000195770)
        /home/stephen/go/src/github.com/ava-labs/coreth/core/tx_cacher.go:63 +0x97
created by github.com/ava-labs/coreth/core.newTxSenderCacher
        /home/stephen/go/src/github.com/ava-labs/coreth/core/tx_cacher.go:55 +0x9f

goroutine 39 [chan receive, 33 minutes]:
github.com/ava-labs/coreth/core.(*txSenderCacher).cache(0xc000195770)
        /home/stephen/go/src/github.com/ava-labs/coreth/core/tx_cacher.go:63 +0x97
created by github.com/ava-labs/coreth/core.newTxSenderCacher
        /home/stephen/go/src/github.com/ava-labs/coreth/core/tx_cacher.go:55 +0x9f

goroutine 40 [chan receive, 33 minutes]:
github.com/ava-labs/coreth/core.(*txSenderCacher).cache(0xc000195770)
        /home/stephen/go/src/github.com/ava-labs/coreth/core/tx_cacher.go:63 +0x97
created by github.com/ava-labs/coreth/core.newTxSenderCacher
        /home/stephen/go/src/github.com/ava-labs/coreth/core/tx_cacher.go:55 +0x9f

goroutine 41 [chan receive, 33 minutes]:
github.com/ava-labs/go-ethereum/vendor/github.com/rjeczalik/notify.(*nonrecursiveTree).dispatch(0xc000095440, 0xc000095380)
        /home/stephen/go/src/github.com/ava-labs/go-ethereum/vendor/github.com/rjeczalik/notify/tree_nonrecursive.go:36 +0xb6
created by github.com/ava-labs/go-ethereum/vendor/github.com/rjeczalik/notify.newNonrecursiveTree
        /home/stephen/go/src/github.com/ava-labs/go-ethereum/vendor/github.com/rjeczalik/notify/tree_nonrecursive.go:29 +0xdc

goroutine 42 [chan receive, 33 minutes]:
github.com/ava-labs/go-ethereum/vendor/github.com/rjeczalik/notify.(*nonrecursiveTree).internal(0xc000095440, 0xc0000953e0)
        /home/stephen/go/src/github.com/ava-labs/go-ethereum/vendor/github.com/rjeczalik/notify/tree_nonrecursive.go:81 +0x58
created by github.com/ava-labs/go-ethereum/vendor/github.com/rjeczalik/notify.newNonrecursiveTree
        /home/stephen/go/src/github.com/ava-labs/go-ethereum/vendor/github.com/rjeczalik/notify/tree_nonrecursive.go:30 +0x108

goroutine 43 [chan receive]:
github.com/ava-labs/go-ethereum/metrics.(*meterArbiter).tick(0x1eb4420)
        /home/stephen/go/src/github.com/ava-labs/go-ethereum/metrics/meter.go:289 +0x78
created by github.com/ava-labs/go-ethereum/metrics.NewMeterForced
        /home/stephen/go/src/github.com/ava-labs/go-ethereum/metrics/meter.go:70 +0x104

goroutine 44 [select]:
github.com/ava-labs/go-ethereum/consensus/ethash.(*Ethash).remote(0xc00019e1c0, 0x0, 0x0, 0x0, 0x0)
        /home/stephen/go/src/github.com/ava-labs/go-ethereum/consensus/ethash/sealer.go:307 +0x532
created by github.com/ava-labs/go-ethereum/consensus/ethash.New
        /home/stephen/go/src/github.com/ava-labs/go-ethereum/consensus/ethash/ethash.go:496 +0x35c

goroutine 103 [IO wait, 29 minutes]:
internal/poll.runtime_pollWait(0x7fbde1bf7c98, 0x72, 0x0)
        /home/stephen/.gvm/gos/go1.13/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc000294098, 0x72, 0x0, 0x0, 0x11acca9)
        /home/stephen/.gvm/gos/go1.13/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /home/stephen/.gvm/gos/go1.13/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc000294080, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/stephen/.gvm/gos/go1.13/src/internal/poll/fd_unix.go:384 +0x1f8
net.(*netFD).accept(0xc000294080, 0xc00028dc60, 0x778604, 0xc000292180)
        /home/stephen/.gvm/gos/go1.13/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc0004cc0a0, 0x5e628260, 0xc00028dc60, 0x4f5ce6)
        /home/stephen/.gvm/gos/go1.13/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc0004cc0a0, 0xc00028dcb0, 0x18, 0xc0002ca000, 0x777b1e)
        /home/stephen/.gvm/gos/go1.13/src/net/tcpsock.go:261 +0x47
net/http.(*Server).Serve(0xc0002920e0, 0x13f6360, 0xc0004cc0a0, 0x0, 0x0)
        /home/stephen/.gvm/gos/go1.13/src/net/http/server.go:2896 +0x286
net/http.(*Server).ListenAndServe(0xc0002920e0, 0xc0002920e0, 0xc0004dab80)
        /home/stephen/.gvm/gos/go1.13/src/net/http/server.go:2825 +0xb7
net/http.ListenAndServe(...)
        /home/stephen/.gvm/gos/go1.13/src/net/http/server.go:3080
github.com/ava-labs/gecko/api.(*Server).Dispatch(0x1eb50e8, 0x11e806b, 0x52)
        /home/stephen/go/src/github.com/ava-labs/gecko/api/server.go:48 +0x118
github.com/ava-labs/gecko/node.(*Node).initAPIServer.func1()
        /home/stephen/go/src/github.com/ava-labs/gecko/node/node.go:380 +0x11b
github.com/ava-labs/gecko/utils/logging.(*Log).RecoverAndPanic(0xc000032240, 0xc00056d7a0)
        /home/stephen/go/src/github.com/ava-labs/gecko/utils/logging/log.go:254 +0x57
created by github.com/ava-labs/gecko/node.(*Node).initAPIServer
        /home/stephen/go/src/github.com/ava-labs/gecko/node/node.go:377 +0x151

goroutine 133 [select]:
github.com/ava-labs/gecko/utils/timer.(*Timer).Dispatch(0xc0005a6540)
        /home/stephen/go/src/github.com/ava-labs/gecko/utils/timer/timer.go:90 +0x1e1
github.com/ava-labs/gecko/utils/timer.(*TimeoutManager).Dispatch(...)
        /home/stephen/go/src/github.com/ava-labs/gecko/utils/timer/timeout_manager.go:40
github.com/ava-labs/gecko/snow/networking/timeout.(*Manager).Dispatch(...)
        /home/stephen/go/src/github.com/ava-labs/gecko/snow/networking/timeout/manager.go:28
github.com/ava-labs/gecko/utils/logging.(*Log).RecoverAndPanic(0xc000032240, 0xc0005a8b10)
        /home/stephen/go/src/github.com/ava-labs/gecko/utils/logging/log.go:254 +0x57
created by github.com/ava-labs/gecko/chains.New
        /home/stephen/go/src/github.com/ava-labs/gecko/chains/manager.go:138 +0xae

goroutine 168 [select, 33 minutes]:
github.com/ava-labs/go-ethereum/accounts/keystore.(*watcher).loop(0xc0002bc200)
        /home/stephen/go/src/github.com/ava-labs/go-ethereum/accounts/keystore/watch.go:94 +0x50d
created by github.com/ava-labs/go-ethereum/accounts/keystore.(*watcher).start
        /home/stephen/go/src/github.com/ava-labs/go-ethereum/accounts/keystore/watch.go:52 +0x59

goroutine 86 [syscall]:
syscall.Syscall6(0xe8, 0x1f, 0xc0004f5f9c, 0x1, 0xffffffffffffffff, 0x0, 0x0, 0xffffffffffffffff, 0x0, 0x4)
        /home/stephen/.gvm/gos/go1.13/src/syscall/asm_linux_amd64.s:44 +0x5
github.com/ava-labs/go-ethereum/vendor/golang.org/x/sys/unix.EpollWait(0x1f, 0xc0004f5f9c, 0x1, 0x1, 0xffffffffffffffff, 0xffffffffffffffff, 0x13dc9c0, 0xc01d312000)
        /home/stephen/go/src/github.com/ava-labs/go-ethereum/vendor/golang.org/x/sys/unix/zsyscall_linux_amd64.go:1689 +0x72
github.com/ava-labs/go-ethereum/vendor/github.com/rjeczalik/notify.(*inotify).loop(0xc0001e4000, 0xc00026e180)
        /home/stephen/go/src/github.com/ava-labs/go-ethereum/vendor/github.com/rjeczalik/notify/watcher_inotify.go:194 +0x77
created by github.com/ava-labs/go-ethereum/vendor/github.com/rjeczalik/notify.(*inotify).lazyinit
        /home/stephen/go/src/github.com/ava-labs/go-ethereum/vendor/github.com/rjeczalik/notify/watcher_inotify.go:134 +0x15b

goroutine 87 [chan receive, 33 minutes]:
github.com/ava-labs/go-ethereum/vendor/github.com/rjeczalik/notify.(*inotify).send(0xc0001e4000, 0xc00026e180)
        /home/stephen/go/src/github.com/ava-labs/go-ethereum/vendor/github.com/rjeczalik/notify/watcher_inotify.go:254 +0xab
created by github.com/ava-labs/go-ethereum/vendor/github.com/rjeczalik/notify.(*inotify).lazyinit
        /home/stephen/go/src/github.com/ava-labs/go-ethereum/vendor/github.com/rjeczalik/notify/watcher_inotify.go:137 +0x1b4

goroutine 88 [chan receive, 33 minutes]:
github.com/ava-labs/go-ethereum/vendor/github.com/rjeczalik/notify.(*inotify).send(0xc0001e4000, 0xc00026e180)
        /home/stephen/go/src/github.com/ava-labs/go-ethereum/vendor/github.com/rjeczalik/notify/watcher_inotify.go:254 +0xab
created by github.com/ava-labs/go-ethereum/vendor/github.com/rjeczalik/notify.(*inotify).lazyinit
        /home/stephen/go/src/github.com/ava-labs/go-ethereum/vendor/github.com/rjeczalik/notify/watcher_inotify.go:137 +0x1b4

goroutine 169 [select]:
github.com/ava-labs/go-ethereum/accounts/keystore.(*KeyStore).updater(0xc0002b60f0)
        /home/stephen/go/src/github.com/ava-labs/go-ethereum/accounts/keystore/keystore.go:205 +0xcc
created by github.com/ava-labs/go-ethereum/accounts/keystore.(*KeyStore).Subscribe
        /home/stephen/go/src/github.com/ava-labs/go-ethereum/accounts/keystore/keystore.go:192 +0x142

goroutine 170 [select, 33 minutes]:
github.com/ava-labs/go-ethereum/accounts.(*Manager).update(0xc00019e2a0)
        /home/stephen/go/src/github.com/ava-labs/go-ethereum/accounts/manager.go:111 +0x1b8
created by github.com/ava-labs/go-ethereum/accounts.NewManager
        /home/stephen/go/src/github.com/ava-labs/go-ethereum/accounts/manager.go:79 +0x4be

goroutine 182 [select, 33 minutes]:
github.com/ava-labs/coreth/miner.(*worker).newWorkLoop(0xc00011dc00, 0xb2d05e00)
        /home/stephen/go/src/github.com/ava-labs/coreth/miner/worker.go:371 +0x283
created by github.com/ava-labs/coreth/miner.newWorker
        /home/stephen/go/src/github.com/ava-labs/coreth/miner/worker.go:237 +0x579

goroutine 183 [select, 33 minutes]:
github.com/ava-labs/coreth/miner.(*worker).resultLoop(0xc00011dc00)
        /home/stephen/go/src/github.com/ava-labs/coreth/miner/worker.go:596 +0xdd
created by github.com/ava-labs/coreth/miner.newWorker
        /home/stephen/go/src/github.com/ava-labs/coreth/miner/worker.go:238 +0x59b

goroutine 184 [select, 33 minutes]:
github.com/ava-labs/coreth/miner.(*worker).taskLoop(0xc00011dc00)
        /home/stephen/go/src/github.com/ava-labs/coreth/miner/worker.go:554 +0xf2
created by github.com/ava-labs/coreth/miner.newWorker
        /home/stephen/go/src/github.com/ava-labs/coreth/miner/worker.go:239 +0x5bd

goroutine 185 [select, 33 minutes]:
github.com/ava-labs/gecko/utils/timer.(*Timer).Dispatch(0xc01065b380)
        /home/stephen/go/src/github.com/ava-labs/gecko/utils/timer/timer.go:90 +0x1e1
github.com/ava-labs/gecko/utils/logging.(*Log).RecoverAndPanic(0xc000298240, 0xc00056c4b0)
        /home/stephen/go/src/github.com/ava-labs/gecko/utils/logging/log.go:254 +0x57
created by github.com/ava-labs/gecko/vms/evm.(*VM).Initialize
        /home/stephen/go/src/github.com/ava-labs/gecko/vms/evm/vm.go:192 +0x5c8

goroutine 186 [chan receive, 33 minutes]:
github.com/ava-labs/gecko/vms/evm.(*VM).Initialize.func6()
        /home/stephen/go/src/github.com/ava-labs/gecko/vms/evm/vm.go:203 +0x58
github.com/ava-labs/gecko/utils/logging.(*Log).RecoverAndPanic(0xc000298240, 0xc00056c4d0)
        /home/stephen/go/src/github.com/ava-labs/gecko/utils/logging/log.go:254 +0x57
created by github.com/ava-labs/gecko/vms/evm.(*VM).Initialize
        /home/stephen/go/src/github.com/ava-labs/gecko/vms/evm/vm.go:200 +0x6d1

goroutine 187 [select]:
github.com/ava-labs/gecko/vms/evm.(*VM).Initialize.func7()
        /home/stephen/go/src/github.com/ava-labs/gecko/vms/evm/vm.go:241 +0xf1
github.com/ava-labs/gecko/utils/logging.(*Log).RecoverAndPanic(0xc000298240, 0xc00056d190)
        /home/stephen/go/src/github.com/ava-labs/gecko/utils/logging/log.go:254 +0x57
created by github.com/ava-labs/gecko/vms/evm.(*VM).Initialize
        /home/stephen/go/src/github.com/ava-labs/gecko/vms/evm/vm.go:238 +0x9a0

goroutine 196 [runnable]:
runtime.goparkunlock(...)
        /home/stephen/.gvm/gos/go1.13/src/runtime/proc.go:310
sync.runtime_notifyListWait(0xc0005aa3d0, 0x0)
        /home/stephen/.gvm/gos/go1.13/src/runtime/sema.go:510 +0xf8
sync.(*Cond).Wait(0xc0005aa3c0)
        /home/stephen/.gvm/gos/go1.13/src/sync/cond.go:56 +0x9d
github.com/ava-labs/gecko/utils/logging.(*Log).run(0xc000032480)
        /home/stephen/go/src/github.com/ava-labs/gecko/utils/logging/log.go:68 +0x313
github.com/ava-labs/gecko/utils/logging.(*Log).RecoverAndPanic(0xc000032480, 0xc00056d300)
        /home/stephen/go/src/github.com/ava-labs/gecko/utils/logging/log.go:254 +0x57
created by github.com/ava-labs/gecko/utils/logging.New
        /home/stephen/go/src/github.com/ava-labs/gecko/utils/logging/log.go:42 +0x14e

goroutine 198 [chan receive, 3 minutes]:
github.com/ava-labs/coreth/eth/filters.(*PublicFilterAPI).timeoutLoop(0xc0106575e0)
        /home/stephen/go/src/github.com/ava-labs/coreth/eth/filters/api.go:83 +0x131
created by github.com/ava-labs/coreth/eth/filters.NewPublicFilterAPI
        /home/stephen/go/src/github.com/ava-labs/coreth/eth/filters/api.go:73 +0x149

goroutine 199 [sync.Cond.Wait]:
runtime.goparkunlock(...)
        /home/stephen/.gvm/gos/go1.13/src/runtime/proc.go:310
sync.runtime_notifyListWait(0xc0005aaad0, 0x14)
        /home/stephen/.gvm/gos/go1.13/src/runtime/sema.go:510 +0xf8
sync.(*Cond).Wait(0xc0005aaac0)
        /home/stephen/.gvm/gos/go1.13/src/sync/cond.go:56 +0x9d
github.com/ava-labs/gecko/utils/logging.(*Log).run(0xc000032540)
        /home/stephen/go/src/github.com/ava-labs/gecko/utils/logging/log.go:68 +0x313
github.com/ava-labs/gecko/utils/logging.(*Log).RecoverAndPanic(0xc000032540, 0xc0005a94a0)
        /home/stephen/go/src/github.com/ava-labs/gecko/utils/logging/log.go:254 +0x57
created by github.com/ava-labs/gecko/utils/logging.New
        /home/stephen/go/src/github.com/ava-labs/gecko/utils/logging/log.go:42 +0x14e

goroutine 213 [sync.Cond.Wait, 33 minutes]:
runtime.goparkunlock(...)
        /home/stephen/.gvm/gos/go1.13/src/runtime/proc.go:310
sync.runtime_notifyListWait(0xc0005ab6d0, 0x0)
        /home/stephen/.gvm/gos/go1.13/src/runtime/sema.go:510 +0xf8
sync.(*Cond).Wait(0xc0005ab6c0)
        /home/stephen/.gvm/gos/go1.13/src/sync/cond.go:56 +0x9d
github.com/ava-labs/gecko/utils/logging.(*Log).run(0xc000032600)
        /home/stephen/go/src/github.com/ava-labs/gecko/utils/logging/log.go:68 +0x313
github.com/ava-labs/gecko/utils/logging.(*Log).RecoverAndPanic(0xc000032600, 0xc0005a97b0)
        /home/stephen/go/src/github.com/ava-labs/gecko/utils/logging/log.go:254 +0x57
created by github.com/ava-labs/gecko/utils/logging.New
        /home/stephen/go/src/github.com/ava-labs/gecko/utils/logging/log.go:42 +0x14e

goroutine 214 [sync.Cond.Wait]:
runtime.goparkunlock(...)
        /home/stephen/.gvm/gos/go1.13/src/runtime/proc.go:310
sync.runtime_notifyListWait(0xc0005ab890, 0x16)
        /home/stephen/.gvm/gos/go1.13/src/runtime/sema.go:510 +0xf8
sync.(*Cond).Wait(0xc0005ab880)
        /home/stephen/.gvm/gos/go1.13/src/sync/cond.go:56 +0x9d
github.com/ava-labs/gecko/utils/logging.(*Log).run(0xc000032780)
        /home/stephen/go/src/github.com/ava-labs/gecko/utils/logging/log.go:68 +0x313
github.com/ava-labs/gecko/utils/logging.(*Log).RecoverAndPanic(0xc000032780, 0xc0005a9c50)
        /home/stephen/go/src/github.com/ava-labs/gecko/utils/logging/log.go:254 +0x57
created by github.com/ava-labs/gecko/utils/logging.New
        /home/stephen/go/src/github.com/ava-labs/gecko/utils/logging/log.go:42 +0x14e

goroutine 224 [sync.Cond.Wait, 33 minutes]:
runtime.goparkunlock(...)
        /home/stephen/.gvm/gos/go1.13/src/runtime/proc.go:310
sync.runtime_notifyListWait(0xc0005abc50, 0x0)
        /home/stephen/.gvm/gos/go1.13/src/runtime/sema.go:510 +0xf8
sync.(*Cond).Wait(0xc0005abc40)
        /home/stephen/.gvm/gos/go1.13/src/sync/cond.go:56 +0x9d
github.com/ava-labs/gecko/utils/logging.(*Log).run(0xc000032a80)
        /home/stephen/go/src/github.com/ava-labs/gecko/utils/logging/log.go:68 +0x313
github.com/ava-labs/gecko/utils/logging.(*Log).RecoverAndPanic(0xc000032a80, 0xc0005a9df0)
        /home/stephen/go/src/github.com/ava-labs/gecko/utils/logging/log.go:254 +0x57
created by github.com/ava-labs/gecko/utils/logging.New
        /home/stephen/go/src/github.com/ava-labs/gecko/utils/logging/log.go:42 +0x14e

goroutine 225 [sync.Cond.Wait]:
runtime.goparkunlock(...)
        /home/stephen/.gvm/gos/go1.13/src/runtime/proc.go:310
sync.runtime_notifyListWait(0xc0005abdd0, 0x19)
        /home/stephen/.gvm/gos/go1.13/src/runtime/sema.go:510 +0xf8
sync.(*Cond).Wait(0xc0005abdc0)
        /home/stephen/.gvm/gos/go1.13/src/sync/cond.go:56 +0x9d
github.com/ava-labs/gecko/utils/logging.(*Log).run(0xc000032b40)
        /home/stephen/go/src/github.com/ava-labs/gecko/utils/logging/log.go:68 +0x313
github.com/ava-labs/gecko/utils/logging.(*Log).RecoverAndPanic(0xc000032b40, 0xc0002286d0)
        /home/stephen/go/src/github.com/ava-labs/gecko/utils/logging/log.go:254 +0x57
created by github.com/ava-labs/gecko/utils/logging.New
        /home/stephen/go/src/github.com/ava-labs/gecko/utils/logging/log.go:42 +0x14e

goroutine 234 [sync.Cond.Wait, 33 minutes]:
runtime.goparkunlock(...)
        /home/stephen/.gvm/gos/go1.13/src/runtime/proc.go:310
sync.runtime_notifyListWait(0xc000576310, 0x0)
        /home/stephen/.gvm/gos/go1.13/src/runtime/sema.go:510 +0xf8
sync.(*Cond).Wait(0xc000576300)
        /home/stephen/.gvm/gos/go1.13/src/sync/cond.go:56 +0x9d
github.com/ava-labs/gecko/utils/logging.(*Log).run(0xc000032c00)
        /home/stephen/go/src/github.com/ava-labs/gecko/utils/logging/log.go:68 +0x313
github.com/ava-labs/gecko/utils/logging.(*Log).RecoverAndPanic(0xc000032c00, 0xc0002288f0)
        /home/stephen/go/src/github.com/ava-labs/gecko/utils/logging/log.go:254 +0x57
created by github.com/ava-labs/gecko/utils/logging.New
        /home/stephen/go/src/github.com/ava-labs/gecko/utils/logging/log.go:42 +0x14e

goroutine 78 [IO wait, 6 minutes]:
internal/poll.runtime_pollWait(0x7fbde1bf7f08, 0x72, 0xffffffffffffffff)
        /home/stephen/.gvm/gos/go1.13/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc0005c0398, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
        /home/stephen/.gvm/gos/go1.13/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /home/stephen/.gvm/gos/go1.13/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0005c0380, 0xc0117c1000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /home/stephen/.gvm/gos/go1.13/src/internal/poll/fd_unix.go:169 +0x1cf
net.(*netFD).Read(0xc0005c0380, 0xc0117c1000, 0x1000, 0x1000, 0xc01739d9e8, 0x4fe16d, 0xc0005c0380)
        /home/stephen/.gvm/gos/go1.13/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc0004d0090, 0xc0117c1000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /home/stephen/.gvm/gos/go1.13/src/net/net.go:184 +0x68
net/http.(*connReader).Read(0xc0118baf90, 0xc0117c1000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /home/stephen/.gvm/gos/go1.13/src/net/http/server.go:785 +0xf4
bufio.(*Reader).fill(0xc0005a48a0)
        /home/stephen/.gvm/gos/go1.13/src/bufio/bufio.go:100 +0x103
bufio.(*Reader).Peek(0xc0005a48a0, 0x4, 0x0, 0x0, 0x0, 0x0, 0xc01739dad0)
        /home/stephen/.gvm/gos/go1.13/src/bufio/bufio.go:138 +0x4f
net/http.(*conn).readRequest(0xc01198e000, 0x13fbbe0, 0xc000324c40, 0x0, 0x0, 0x0)
        /home/stephen/.gvm/gos/go1.13/src/net/http/server.go:962 +0xb3b
net/http.(*conn).serve(0xc01198e000, 0x13fbbe0, 0xc000324c40)
        /home/stephen/.gvm/gos/go1.13/src/net/http/server.go:1817 +0x6d4
created by net/http.(*Server).Serve
        /home/stephen/.gvm/gos/go1.13/src/net/http/server.go:2927 +0x38e
```

**Operating System**
This has only been replicated on Ubuntu 18.04.

### PR DESCRIPTION
**Pull request by StephenButtolph**
Remove cgo signal handlers that were non-compliant with the [go signal handling specification](https://golang.org/src/os/signal/doc.go?h=If+the+non-Go+code+installs+any+signal+handlers). Resolves #8.

### CODE REVIEW

File: node/node.go [hunk 1]
```diff
@@ -143,12 +149,17 @@ func errorHandler(_err *C.struct_SalticidaeCError, fatal C.bool, asyncID C.int32
...
 	n.EC = salticidae.NewEventContext()
+	n.TCall = salticidae.NewThreadCall(n.EC)
 
-	// Set up interrupt signal and terminate signal handlers
-	evInt := salticidae.NewSigEvent(n.EC, salticidae.SigEventCallback(C.onTerm), nil)
-	evInt.Add(salticidae.SIGINT)
-	evTerm := salticidae.NewSigEvent(n.EC, salticidae.SigEventCallback(C.onTerm), nil)
-	evTerm.Add(salticidae.SIGTERM)
+	c := make(chan os.Signal, 1)
+	signal.Notify(c, os.Interrupt)
```
Comment (adasari) [inline node/node.go:155]: How about creating signal callback func ? this can be used across application. just a suggestion.
```
// invoke utils.go
NewNotifierOnSignal(func(s os.Signal) {
            n.TCall.AsyncCall(salticidae.ThreadCallCallback(C.onTerm), nil)
})
```

```
// utils.go
type  SignalCallback func(s os.Signal)

func NewNotifierOnSignal(callback SignalCallback, sig ...os.Signal) {
    if callback != nil && len(sig) > 0 {
        go func() {
            sigChan := make(chan os.Signal, 1)
            defer signal.Stop(sigChan)

            signal.Notify(sigChan, sig...)
            select {
            case s := <-sigChan:
                callback(s)
            }
        }()
    }
}
```

Comment (StephenButtolph) [reply node/node.go]: Updated signal handling into utils.
