### PR TITLE
Use Add instead of Push to correctly order timed txs in event heap

### LINKED ISSUE #233: platformvm unissuedEvents ordering
**Describe the bug**
The IssueTx function in platformvm [modifies the vm.unissuedEvents](https://github.com/ava-labs/gecko/blob/master/vms/platformvm/service.go#L1278) heap independent of the startTime or endTime ordering 

**To Reproduce**
IssueTx's and check the heap order of tx's startTime or endTime values

**Expected behavior**
It should use the EventHeap's Add function or heap.push to add new events.

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

### PR DESCRIPTION
**Pull request by aaronbuchwald**
Fixes #233

### CODE REVIEW

File: vms/platformvm/service.go [hunk 1]
```diff
@@ -1290,7 +1290,7 @@ func (service *Service) IssueTx(_ *http.Request, args *IssueTxArgs, response *Is
 		service.vm.unissuedAtomicTxs = append(service.vm.unissuedAtomicTxs, tx)
 		response.TxID = tx.ID()
 	default:
-		return errors.New("Could not parse given tx. Must be a TimedTx, DecisionTx, or AtomicTx")
+		return errors.New("Could not parse given tx. Must not be a TimedTx, DecisionTx, or AtomicTx")
```
Comment (StephenButtolph) [inline vms/platformvm/service.go:1293]: This error message seems to be confusing. Can we make it clear that the provided transaction has to be either a `TimedTx`, `DecisionTx`, or an `AtomicTx`?

"Could not parse given tx. Provided tx needs to be a TimedTx, DecisionTx, or AtomicTx"

Comment (aaronbuchwald) [reply vms/platformvm/service.go]: Updated
